apiVersion: v1
kind: ResourceQuota
metadata:
  name: goonline-dev-cpu-mem-quota
  namespace: goonline-dev
spec:
  hard:
    cpu: '1'
    memory: 1Gi
    pods: '5'
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: goonline-test-cpu-mem-quota
  namespace: goonline-test
spec:
  hard:
    cpu: '1'
    memory: 1Gi
    pods: '5'
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: goonline-staging-cpu-mem-quota
  namespace: goonline-staging
spec:
  hard:
    cpu: '1'
    memory: 1Gi
    pods: '5'